### ISSUE TITLE
Link our Matrix room from the readme - `#matrix-public-archive:matrix.org`

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-public-archive#140]
Add a link for https://matrix.to/#/#matrix-public-archive:matrix.org to the project readme so people can jump in and ask questions.

Which badge source is the best?

**Comment by pdurbin** [comment]
I'm heavily influenced by https://atrisovic.github.io/dataverse-badge/ by @atrisovic but I like https://shields.io for badges.

You can just fill in their form to get an SVG  like this: https://img.shields.io/badge/chat-%23matrix--public--archive-brightgreen

Here are a couple screenshots:

<img width="851" alt="Screen Shot 2022-12-03 at 12 27 48 PM" src="https://user-images.githubusercontent.com/21006/205453738-03e647c6-82ce-42b0-a273-70333391e833.png">
<img width="851" alt="Screen Shot 2022-12-03 at 12 27 51 PM" src="https://user-images.githubusercontent.com/21006/205453740-bf4b3626-c135-4215-8977-4fc5ad9cfd6a.png">

An additional thought for you... now that we have a public preview of messages (#149), you could also link (with a second badge?) to https://view.matrix.org/alias/%23matrix-public-archive:matrix.org so people could get a preview without even having a Matrix account. That's what I do at https://chat.dataverse.org ... the main call to action is "View Log" with the idea that if people like what they see, they can create a Matrix account, sign in, and start chatting. Here's a screenshot:

<img width="920" alt="Screen Shot 2022-12-03 at 12 31 40 PM" src="https://user-images.githubusercontent.com/21006/205453935-68993f3a-3855-4d7b-9769-0e96449b832b.png">
