### ISSUE TITLE
Permalinks to the archive itself? Rather than just `https://matrix.to/#/…` permalinks

### ISSUE THREAD

**Issue by sideshowbarker** [matrix-org/matrix-public-archive#146]
I’ve gotten far enough along with testing to now see that the available message permalinks are `https://matrix.to/#/…` that to be opened/followed require the use of a Matrix client.

It would be useful to also have links to the archived messages themselves — that is, URLs for the Matrix Public Archive copies of the messages themselves.

**Comment by sideshowbarker** [comment]
…but after looking at https://github.com/matrix-org/matrix-public-archive/issues/137, I now wonder if what’s suggested in the issue description is already implemented but just not showing up in my test instance for some reason…

**Comment by MadLittleMods** [comment]
@sideshowbarker What you're looking for is tracked by https://github.com/matrix-org/matrix-public-archive/issues/137

The link in the UI doesn't exist, that "link" you see in the other issue, was using the `matrix.to` link before and I switched to a "Copy permalink" context menu option via https://github.com/vector-im/hydrogen-web/pull/921

Currently, you can manually add `?at=$xxx` to the Matrix Public Archive URL to highlight that event ID on the page though, ex. `/r/some-room:synapse.server/date/2022/04/14?at=$FmQbig8PySJF9tLQhdzO0KOVvySP9X8Cg0XuqNxZJqg`. This was added in https://github.com/matrix-org/matrix-public-archive/pull/123

**Comment by bkil** [comment]
Actually, not all (included or generated) matrix.to links were substituted. See #236
