### ISSUE TITLE
Allow public preview of #matrix-public-archive

### ISSUE THREAD

**Issue by pdurbin** [matrix-org/matrix-public-archive#149]
Would it be possible to open up #matrix-public-archive so that messages can be previewed at https://view.matrix.org/alias/%23matrix-public-archive:matrix.org ?

This is the error I get:

`User @2985302:matrix.org not in room !SzoPnANsRYxITaDPaJ:matrix.org, and room previews are disabled (M_FORBIDDEN)`

Here's the error in context:

<img width="865" alt="Screen Shot 2022-12-02 at 7 49 11 PM" src="https://user-images.githubusercontent.com/21006/205414117-cd2a8ab2-adc1-4570-ba6f-9fe7d3ca53ee.png">

https://view.matrix.org/alias/%23matrix:matrix.org for example works fine. Here's a screenshot:

<img width="1078" alt="Screen Shot 2022-12-02 at 7 52 07 PM" src="https://user-images.githubusercontent.com/21006/205414216-b41272da-e9b6-46f9-b3e8-b6cbc8035c59.png">

Thanks for considering this.

Related:

- #140

**Comment by MadLittleMods** [comment]
Good point! Updated the `history_visibility` to `world_readable` ✅
