### ISSUE TITLE
Add Oct 2022 demo video to README

### ISSUE THREAD

**Issue by pdurbin** [matrix-org/matrix-public-archive#150]
Matrix Public Archive is awesome but it wasn't on my radar until I heard about it on [Matrix Live](https://matrix.org/blog/2022/08/05/this-week-in-matrix-2022-08-05#matrix-public-archive-website): https://www.youtube.com/watch?v=UT6KSEqDUf8&t=548s

Should we link to this video from the README? I find it absolutely inspiring! It works! It's coming!

<img width="1842" alt="Screen Shot 2022-12-03 at 12 59 38 PM" src="https://user-images.githubusercontent.com/21006/205455891-ef433578-03e4-47b9-bb44-afc22ce52f35.png">

**Comment by MadLittleMods** [comment]
It would be fine to link for now 👍

We can also link https://www.youtube.com/watch?v=6KHQSeJTXm0&t=583s to give a better intro.

We can always record a better and more up to date demo later
