### ISSUE TITLE
Better Caching for assets - serve assets from subdirectory

### ISSUE THREAD

**Issue by Cyberes** [matrix-org/matrix-public-archive#160]
Hi guys, really like this project and looking forward to see where it goes.

I've got a question: why are you setting `cache-control: public, max-age=0` on all of the static assets? There are a few large assets that would benefit from Cloudflare caching. I've been using cache rules to bypass this header but I am unable easily modify `/Inter-Regular-89d406b0.woff2?v=3.13` as it is served from the root domain and has a version tag on it. I set rules for `/css` and `/js` but I will have to hard-code this file which isn't ideal.

I suppose a cache value of at least a day would be good and serving the fonts from a path such as `/fonts` would be nice too.

**Comment by Cyberes** [comment]
My own installation.

**Comment by MadLittleMods** [comment]
Thanks for the clarifying @Cyberes!

We're not setting cache headers anywhere in the codebase at the moment. So this would be whatever defaults are coming out of the Node.js Express server or Cloudflare. Would it make sense to keep the cache header responsibility in the layer above the app (part of specific deployment configurations)? Whether that be nginx, Cloudflare, etc.

Assets being served on the root domain is a Hydrogen thing. Talking with Bruno (Hydrogen maintainer) before about it, he was leaning towards us having to reprocess the Hydrogen styles with PostCSS to change the path references. Adjusting this would make the overrides easier. Would that be sufficient to solving this situation?

See https://github.com/matrix-org/matrix-public-archive/issues/132 for other ways we're thinking about speeding up the assets.

**Comment by Cyberes** [comment]
> Would it make sense to keep the cache header responsibility in the layer above the app (part of specific deployment configurations)?

Right now, I think it would. But maybe in the future maybe consider settling on a cache value? Don't worry about it right now, serving assets from `/img`, `/js` (and so on) is a much higher priority.

**Comment by MadLittleMods** [comment]
All of the Hydrogen assets come in one directory (`hydrogen-view-sdk/asset-build/assets/`) in the package. We currently serve it with [this snippet](https://github.com/matrix-org/matrix-public-archive/blob/b0cee80253eb74e412f7515b147f6568ec94aef6/server/routes/install-routes.js#L39-L43). It would probably be easiest to rewrite the paths in the CSS and serve them at `/hydrogen-assets` instead of filtering and splitting them up into `/img` `/js`, `/styles`, etc

**Comment by MadLittleMods** [comment]
This was further changed in https://github.com/matrix-org/matrix-public-archive/pull/175 where everything is served from `/assets/...` and all filenames have hashes so they can be cached forever 🚀
