### ISSUE TITLE
Sorting is different between browsers

### ISSUE THREAD

**Issue by Miepee** [matrix-org/matrix-public-archive#218]
Sorting is different between browsers when viewing the room directory homepage:

Firefox 112.0.2 (unexpected weird sort ❌) | Chromium  112.0.5615.165 (expected ✅)
--- | ---
![grafik](https://user-images.githubusercontent.com/38186597/236521123-482a721b-e7e1-4eea-a708-866dc8c7b9c4.png) | ![grafik](https://user-images.githubusercontent.com/38186597/236521292-96051325-2a40-409a-b26b-4c4b1dc7b84c.png)

Not sure how Safari behaves.

---

*As [discussed in Matrix Public Archive room](https://matrix.to/#/!SzoPnANsRYxITaDPaJ:matrix.org/$ix-cyDJYix7NXfPtOojKOA-ialABS_8gFl3vy7l0eoA?via=matrix.org&via=matrix.vgorcum.com&via=tchncs.de)*

**Comment by MadLittleMods** [comment]
Reminds me of https://github.com/matrix-org/matrix.org/issues/965 (another Firefox only issue with inexplicable sorting differences)
