### ISSUE TITLE
Clicking on a member profile leads to an empty failure page

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#242]
If I view the timeline of a room and I click on the user avatar, it leads to the following URL:

* https://archive.matrix.org/member/@bkil:matrix.org

Containing the following error message:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /member/@bkil:matrix.org</pre>
</body>
</html>
```

If it is due to the respective backend feature not being implemented, all such links should be removed from the user interface.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/matrix-org/matrix-public-archive/issues/78
