### ISSUE TITLE
Video player does not show

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#252]
Hydrogen does render it.

* https://archive.matrix.org/r/fun:grin.hu/date/2023/04/12T00:12:47?at=$E3Jc1XSYVl1qwWsS0K1DtwyZDqd-22lTlV_Jh483InI

```
{
  "content": {
    "body": "rms-whatstands4 (1).webm",
    "info": {
      "duration": 114643,
      "h": 250,
      "mimetype": "video/webm",
      "size": 3193152,
      "thumbnail_info": {
        "h": 250,
        "mimetype": "image/jpeg",
        "size": 9937,
        "w": 444
      },
      "thumbnail_url": "mxc://grin.hu/XfUJLsVflXFtoBbEjZogpviN",
      "w": 444
    },
    "msgtype": "m.video",
    "url": "mxc://grin.hu/YRMSuaSriixvKqoMhaCqOotI"
  },
  "origin_server_ts": 1680107698163,
  "room_id": "!CwMDVzZXiVUzvlBHdn:grin.hu",
  "sender": "@guih48:grin.hu",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$E3Jc1XSYVl1qwWsS0K1DtwyZDqd-22lTlV_Jh483InI",
  "user_id": "@guih48:grin.hu"
}
```

![archive matrix org_issues_252_video_not_showing](https://github.com/matrix-org/matrix-public-archive/assets/818763/71a1fb5b-c65a-464a-821d-9b3c46efc328)

**Comment by MadLittleMods** [comment]
This seems to work fine for me even with JavaScript disabled (tested with Chrome and Firefox). Perhaps your browser or some extensions is blocking it. Or the homeserver had a hiccup and couldn't serve it at the time.

![](https://github.com/matrix-org/matrix-public-archive/assets/558581/52da7ebe-f36a-41aa-bead-c5bf555fdd8b)

**Comment by bkil** [comment]
Sorry, this one was on my side. Works on another browser. An extension blocked the video, but works if whitelisted.
