### ISSUE TITLE
Render room description in the static HTML of the timeline view

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#256]
It is already shown on the room search result page. It would be helpful for everyone stumbling upon any kind of deep permalink.

It should also be a valuable SEO addition.

I see it is included in the JSON as well in the body.

**Comment by MadLittleMods** [comment]
The Matrix Public Archive uses [Hydrogen](https://github.com/vector-im/hydrogen-web) under the hood and this is an upstream feature in Hydrogen itself, see https://github.com/vector-im/hydrogen-web/issues/433
