### ISSUE TITLE
FAQ: not an archiver bot, but a SSR noJS matrix client to share web permalinks

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#270]

**Comment by bkil** [comment]
People started another wave of banning the bot across various rooms after seeing the name change, so something must still not have been completely clear in the FAQ.

**Comment by bkil** [comment]
People considered reasonable and knowledgeable are still explaining in multiple rooms that their motivation for the ban list additions were them not wishing for you to **archive** (i.e., store indefinitely, log) all of their content. 🤷

**Comment by MadLittleMods** [comment]
Iterating on the docs is no problem :+1:. If you want to clarify anything, feel free to send a PR

Here is how that's currently explained:

https://github.com/matrix-org/matrix-public-archive/blob/e4800852fff23cd4a03ef05282c71f58516cf2a4/docs/faq.md?plain=1#L35-L38
