### ISSUE TITLE
Add NSFW safe search filter to room directory landing page

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-public-archive#89]
Add NSFW safe search filter to room directory landing page.

We can put placeholder `RoomCards` for any rooms caught in the filter. This way our grid of rooms is even, we don't throw off pagination by trying to fetch more than needed and filter down, people are aware of content they are not seeing, and we don't upset our Google SEO rankings as much.

![](https://user-images.githubusercontent.com/558581/196606265-51f4b87e-6769-4475-8b1d-2ac7525eac19.png)

The Safe search toggle control above the grid of rooms:

![](https://user-images.githubusercontent.com/558581/202874262-372acf8d-14bd-46f0-a086-1d54c6cd1852.png)

### What is considered NSFW?

Any room with `NSFW`, `porn`, `nudes` (maybe other keywords, `sex`, `18+`) in the title or topic/description. This won't be exhaustive or completely effective but seems like it would do a decent job.

### Dev notes

Default to safe search on which keeps it out of the query parameters by default.

---

Checkbox styles look something like http://jsfiddle.net/MadLittleMods/x049hLb7/

#### Prior art

Good language and semantics around how Google explains safe search.

![](https://user-images.githubusercontent.com/558581/196607888-0453b60e-8c29-4f9f-b03c-7d027839e324.png)

**Comment by Jem256** [comment]
hey @MadLittleMods I'd like to give this a try. But I'd like some clarification on what the t and vm are in the code `render(t, vm)` and how the app is doing a search for the rooms

**Comment by MadLittleMods** [comment]
> clarification on what the t and vm are in the code `render(t, vm)`

@Jem256 It's from Hydrogen so you'll get a better picture by exploring that codebase first, see [`vector-im/hydrogen-web` -> `doc/UI/ui.md`](https://github.com/vector-im/hydrogen-web/blob/dbbbb1c29ababbcbe3f933b2a9424e3c0fc00ec5/doc/UI/ui.md):

> In views based on `TemplateView`, you will see a render method with a `t` argument.  
> `t` is `TemplateBuilder` object passed to the render function in `TemplateView`. It also takes a data object to render and bind to, often called `vm`, short for view model from the MVVM pattern Hydrogen uses.
>
> *-- [`vector-im/hydrogen-web` -> `doc/UI/ui.md#templateview`](https://github.com/vector-im/hydrogen-web/blob/dbbbb1c29ababbcbe3f933b2a9424e3c0fc00ec5/doc/UI/ui.md#templateview)*


---

> how the app is doing a search for the rooms

We're fetching the rooms on the room directory landing page in [`server/routes/room-directory-routes.js#L47`](https://github.com/matrix-org/matrix-public-archive/blob/f95086df0d22393376916e087bc0ced09ba3f389/server/routes/room-directory-routes.js#L47) via [`fetchPublicRooms`](https://github.com/matrix-org/matrix-public-archive/blob/f95086df0d22393376916e087bc0ced09ba3f389/server/lib/matrix-utils/fetch-public-rooms.js) which uses the [`/publicRooms`](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv3publicrooms) API endpoint. But as mentioned in the issue description, we don't need to change the way we fetch rooms at all.

We just need to detect that a room falls in the NSFW bucket and put the NSFW version of the `RoomCard` in place depending on whether safe search is enabled or not.
